package se.kth.iv1201.recruitment.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import se.kth.iv1201.recruitment.entity.User;
import se.kth.iv1201.recruitment.repository.UserRepository;

@Controller    // This means that this class is a Controller
public class RegisterController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/register")
    public String getRegister(Model model){
        User user = new User();
        model.addAttribute("user", user);
        return "register";
    }

    @PostMapping(path="/register")
    public String postRegister(@ModelAttribute User user) {

        System.out.println(user.getUsername());
        user.setEnabled(true);
        userRepository.save(user);
        return "home";
    }
}